CREATE DATABASE IF NOT EXISTS stargazer;

USE stargazer;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT,
    name VARCHAR(35) NOT NULL,
    email VARCHAR(35) NOT NULL,
    password VARCHAR(35) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
    id INT AUTO_INCREMENT,
    name VARCHAR(35) NOT NULL,
    description VARCHAR(100) NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lat DECIMAL(9,6),
    lon DECIMAL(9,6),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS locations (
    id INT AUTO_INCREMENT,
    name VARCHAR(35) NOT NULL,
    description VARCHAR(100) NOT NULL,
    lat DECIMAL(9,6),
    lon DECIMAL(9,6),
    PRIMARY KEY (id)
);